### ISSUE TITLE
MAPI Mail Store Endpoint Test Fail

### ISSUE THREAD

**Issue by aledr** [phr0gz/Apache-reverse-proxy-for-Exchange-2010-2013-2016#1]
Hi!

Was you able to get success on the test?

While trying https://testconnectivity.microsoft.com I get:

` "RPC_OUT_DATA /rpc/rpcproxy.dll?55cb32b9-45c1-4921-bac4-2fe72da55552@mydomain.com:6001 HTTP/1.1" 401 -`

`(70007)The timeout specified has expired: AH01095: prefetch request body failed to ...`
`(70008)Partial results are valid but processing is incomplete: AH01095: prefetch request body failed to`

**Comment by phr0gz** [comment]
Hello aledr, I don't have any issues.
![screenshoot of the exchange AS test](http://www.hostingpics.net/viewer.php?id=243879test.png)

BTW: 401 is when exchange is asking for credential.

**Comment by aledr** [comment]
Thats weird... Please take a look, maybe I'm missing a detail.

<VirtualHost default:443>

    ServerName mail.mydomain.com
    ServerAlias autodiscover.mydomain.com
    ServerAdmin support@mydomain.com
    ErrorLog /var/log/apache2/mail.mydomain.com-error_log
    TransferLog /var/log/apache2/mail.mydomain.com-access_log

    SSLEngine On
    SSLProxyEngine On
    SSLCertificateFile /etc/apache2/ssl.crt/mail_mydomain_com.crt
    SSLCertificateKeyFile /etc/apache2/ssl.key/mail_mydomain_com.key

    SSLProtocol All -SSLv2 -SSLv3
    SSLCipherSuite "HIGH:!aNULL:!MD5:!3DES:!CAMELLIA:!AES128"
    Header always set Strict-Transport-Security "max-age=31536000;"

    ProxyRequests Off
    ProxyPreserveHost On
    RequestHeader edit Transfer-Encoding Chunked chunked early
    RequestHeader unset Accept-Encoding
    ProxyVia Full
    TimeOut 1800
    ProxyTimeout 1800
    KeepAliveTimeout 1800

    ProxyPass / https://192.168.10.224/ retry=0

    <Proxy *>
        Order deny,allow
        Allow from all
    </Proxy>
</VirtualHost>

**Comment by phr0gz** [comment]
Where are the following params? :
```
SSLProxyVerify none
SSLProxyCheckPeerCN off
SSLProxyCheckPeerName off
```
Because you are using an IP with TLS (see below) you can't verify the certificate...
```
ProxyPass / https://192.168.10.224/ retry=0
```

You may also delete the "retry=0" at the end, just for the test.

**Comment by aledr** [comment]
- Exchange ActiveSync - Success
- Exchange ActiveSync Autodiscover- Success
- Synchronization, Notification, Availability, and Automatic Replies - Success

This last one was failing before and was the exactly same configuration.
Anyway, thanks a lot!

**Comment by aledr** [comment]
Sorry for the noise...
The problem is on the Outlook Connectivity Test.

Apache Log:

`[Tue Jan 10 18:51:15.862492 2017] [proxy_http:error] [pid 6525] (70007)The timeout specified has expired: [client 40.85.91.8:56648] AH01095: prefetch request body failed to 123.123.123.123:443 (123.123.123.123) from 40.85.91.8 ()
[Tue Jan 10 18:51:15.864223 2017] [proxy_http:error] [pid 6525] (70008)Partial results are valid but processing is incomplete: [client 40.85.91.8:56648] AH01095: prefetch request body failed to 123.123.123.123:443 (123.123.123.123) from 40.85.91.8 ()
`

![error](https://cloud.githubusercontent.com/assets/47945/21824460/ad381c3c-d766-11e6-9233-426c1a730e5f.png)

**Comment by phr0gz** [comment]
Seems not related to the Apache reverse proxy.
https://community.spiceworks.com/topic/843800-ping-the-mapi-mail-store-fail
```


Get-OutlookAnywhere showed ExternalHostName wrong.mydomain.com.

To fix it Get-OutlookAnywhere | Set-OutlookAnywhere -ExternalHostName 'correct.mydomain.com'

﻿There were a number of other places where that wrong name was used. Finding and fixing them all solved it.
```

**Comment by aledr** [comment]
Just validated all URLs and are fine.

```
Get-OutlookAnywhere
Get-EcpVirtualDirectory
Get-OwaVirtualDirectory
Get-WebServicesVirtualDirectory
Get-ActiveSyncVirtualDirectory
Get-OabVirtualDirectory
Get-MapiVirtualDirectory
```

Maybe I'll try to create and exclusive URL for Outlook Anywhere and test again.

**Comment by phr0gz** [comment]
Feel free to re-open the issue.
