### ISSUE TITLE
Outlook isnt working. Webmail works fine

### ISSUE THREAD

**Issue by hermandelul** [phr0gz/Apache-reverse-proxy-for-Exchange-2010-2013-2016#2]
Hello.

ive setup up the virtual host. but the outlook keeps asking for credentials. 
apache is giving an error at the same time:
POST /mapi/nspi/?MailboxId=fab1953a-57c4-496b-a2df-19ff6cc64823@vd-loop.com HTTP/1.0

owa etc works fine.
testconnectivity from ms said this:
Testing the address book "Check Name" operation for user wouter@vd-loop.com against server mail.vd-loop.com.
`
A protocol layer error occured. HttpStatusCode: 401FailureLID: 47372FailureInfo: ###### REQUEST [2017-10-31T15:34:42.7625005Z] ######POST /mapi/nspi/?mailboxId=fab1953a-57c4-496b-a2df-19ff6cc64823@vd-loop.com HTTP/1.1Content-Type: application/octet-stream User-Agent: MapiHttpClient X-RequestId: 09d8c543-4f5b-4692-b0bd-4f9dd6993c99:1 X-ClientInfo: facc3724-146a-4bf7-a535-6812b7424b12:1 X-ClientApplication: MapiHttpClient/15.1.819.0 X-RequestType: Bind Authorization: Basic [truncated] Host: mail.vd-loop.com Content-Length: 45 --- REQUEST BODY [+0.086] ---..[BODY SIZE: 45]--- REQUEST SENT [+0.086] ---###### RESPONSE [+0.186] ######HTTP/1.1 401 UnauthorizedConnection: keep-alive request-id: 384762fb-0d61-4541-a0a6-d25f6d3cb2a4 X-FailureContext: FrontEnd;401;VW5hdXRob3JpemVk;;;; X-FEServer: MS Content-Length: 0 Date: Tue, 31 Oct 2017 15:34:43 GMT Server: nginx Via: 1.0 mail.vd-loop.com (Apache/2.4.6) WWW-Authenticate: Basic [truncated] X-Powered-By: ASP.NET --- RESPONSE BODY [+0.186] ------ RESPONSE DONE [+0.186] ---###### EXCEPTION THROWN [+0.186] ######HTTP Response Headers:Connection: keep-aliverequest-id: 384762fb-0d61-4541-a0a6-d25f6d3cb2a4X-FailureContext: FrontEnd;401;VW5hdXRob3JpemVk;;;;X-FEServer: MSContent-Length: 0Date: Tue, 31 Oct 2017 15:34:43 GMTServer: nginxVia: 1.0 mail.vd-loop.com (Apache/2.4.6)WWW-Authenticate: Basic realm=mail.vd-loop.comX-Powered-By: ASP.NETHttpStatusCode: 401 UnauthorizedElapsed Time: 187 ms.
--

`

what can i do to solve it?

**Comment by phr0gz** [comment]
hello, you need first to verify that basic authentication is enabled for mapi:
On exchange powershell: ```Get-MapiVirtualDirectory | select *AuthenticationMethods | fl```
If it is you can try this url: ```https://fqdn/mapi/emsmdb/?showdebug=yes```
And also check the IIS log.

**Comment by hermandelul** [comment]
hello, 

ive enabled Basic Auth for ews and mapi, than its fully working, thanks for the fast response
