### ISSUE TITLE
Authentication Errors

### ISSUE THREAD

**Issue by donasmello** [phr0gz/Apache-reverse-proxy-for-Exchange-2010-2013-2016#4]
Do you still use this configuration?  Testing with basic authentication with forms based auth and we are getting authentication errors all of a sudden on exchange 2013.  returns owa/auth/errorfe.aspx?httpCode=500.

I looked into this pretty extensively and haven't been able to figure out why this only recently started happening.  Seems related to patches either on proxy server or exchange.

**Comment by djdill** [comment]
@donasmello 
Ended up using Nginx as we had issues too
https://gist.github.com/Brainiarc7/439e2cdf1dfc5482a4e9

Or some like the above code

**Comment by phr0gz** [comment]
Still using it with the last exchange 2016 cu:
```
[PS] C:\Windows\system32>Get-ExchangeServer | Format-List Name,Edition,AdminDisplayVersion


Name                : EXCH1
Edition             : Enterprise
AdminDisplayVersion : Version 15.1 (Build 1979.3)
```

**Comment by donasmello** [comment]
Thanks for the feedback. Worked on it for a few days and ended up being an issue with a Load Balancer that sits in front of our proxies.  We have a weird setup where normally the LB could serve this purpose but these proxy servers sit behind it to do this for the time being.  I think it was related to SSL Offloading on the LB but haven't fully investigated yet.  Anyway, confirmed that the apache config is still working @phr0gz!  Thanks for your feedback as well @djdill
